#!/bin/bash

# Update apt cache.
sudo apt-get update

# Install Nginx.
sudo apt-get install -y nginx

# Set the home page.
echo "<html><body><h2>Welcome to Azure! My name is $(A. Enriquez).</h2></body></html>" | sudo tee -a /var/www/html/index.html


az vm create \
  --resource-group "[sandbox resource group name]" \
  --name Enriquez-vm \
  --public-ip-sku Standard \
  --image Ubuntu2204 \
  --admin-username azureuser \
  --generate-ssh-keys  


az vm extension set \
  --resource-group "[sandbox resource group name]" \
  --vm-name Enriquez-vm \
  --name customScript \
  --publisher Microsoft.Azure.Extensions \
  --version 2.1 \
  --settings '{"fileUris":["https://github.com/AEprogs/Azure/edit/main/Nginx"]}' \
  --protected-settings '{"commandToExecute": "./configure-nginx.sh"}' 
